const GAME_PARAMETERS = [
  {
    playerCount: 5,
    missionsBreakdown: [
      { missionIndex: 1, numberOfPlayers: 2, team: [], votes: [] },
      { missionIndex: 2, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 3, numberOfPlayers: 2, team: [], votes: [] },
      { missionIndex: 4, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 5, numberOfPlayers: 3, team: [], votes: [] },
    ],
    roles: ["Merlin", "Good guy", "Good guy", "Assassin", "Bad guy"],
  },
  {
    playerCount: 6,
    missionsBreakdown: [
      { missionIndex: 1, numberOfPlayers: 2, team: [], votes: [] },
      { missionIndex: 2, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 3, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 4, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 5, numberOfPlayers: 4, team: [], votes: [] },
    ],
    roles: [
      "Merlin",
      "Good guy",
      "Good guy",
      "Good guy",
      "Assassin",
      "Bad guy",
    ],
  },
  {
    playerCount: 7,
    missionsBreakdown: [
      { missionIndex: 1, numberOfPlayers: 2, team: [], votes: [] },
      { missionIndex: 2, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 3, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 4, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 5, numberOfPlayers: 4, team: [], votes: [] },
    ],
    roles: [
      "Merlin",
      "Good guy",
      "Good guy",
      "Good guy",
      "Assassin",
      "Bad guy",
      "Bad guy",
    ],
  },
  {
    playerCount: 8,
    missionsBreakdown: [
      { missionIndex: 1, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 2, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 3, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 4, numberOfPlayers: 5, team: [], votes: [] },
      { missionIndex: 5, numberOfPlayers: 5, team: [], votes: [] },
    ],
    roles: [
      "Merlin",
      "Good guy",
      "Good guy",
      "Good guy",
      "Good guy",
      "Assassin",
      "Bad guy",
      "Bad guy",
    ],
  },
  {
    playerCount: 9,
    missionsBreakdown: [
      { missionIndex: 1, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 2, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 3, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 4, numberOfPlayers: 5, team: [], votes: [] },
      { missionIndex: 5, numberOfPlayers: 5, team: [], votes: [] },
    ],
    roles: [
      "Merlin",
      "Good guy",
      "Good guy",
      "Good guy",
      "Good guy",
      "Good guy",
      "Assassin",
      "Bad guy",
      "Bad guy",
    ],
  },
  {
    playerCount: 10,
    missionsBreakdown: [
      { missionIndex: 1, numberOfPlayers: 3, team: [], votes: [] },
      { missionIndex: 2, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 3, numberOfPlayers: 4, team: [], votes: [] },
      { missionIndex: 4, numberOfPlayers: 5, team: [], votes: [] },
      { missionIndex: 5, numberOfPlayers: 5, team: [], votes: [] },
    ],
    roles: [
      "Merlin",
      "Good guy",
      "Good guy",
      "Good guy",
      "Good guy",
      "Good guy",
      "Assassin",
      "Bad guy",
      "Bad guy",
      "Bad guy",
    ],
  },
];

export default GAME_PARAMETERS;
